### ISSUE TITLE
Any chance for 5.7 support?

### ISSUE THREAD

**Issue by TryTryAgain** [jasonholtzapple/check_mysql_counters#10]
We are seeing an issue with the separate Status Variables and System Variables, among other things. Is this in the pipeline?

**Comment by jasonholtzapple** [comment]
There haven't been any requests and I'm not using it myself. If anyone else would like to see it add a comment please - also mention whether you need Oracle or Percona.

**Comment by TryTryAgain** [comment]
Thanks! I'm working with a PHP wizard now. We've gotten the checks working, woohoo, now working on getting the graphing working. I'll try and have him fork and add his changes for a possible pull request to merge.

**Comment by siliconalchemy** [comment]
A quick way to get this to work with 5.7 is to add this to my.cnf:
```
show_compatibility_56 = on
```
And hack the regex in check_mysql_counters from:
`if ((preg_match("/^5\.6\./", $version['VERSION']) and (preg_match("/percona/i", $version['VERSION_COMMENT'])))) {`
to
`if ((preg_match("/^5\.[67]\./", $version['VERSION']) and (preg_match("/percona/i", $version['VERSION_COMMENT'])))) {`

**Comment by flcaza** [comment]
Hi, 
I modify 2 files and if you want to upload it on git it is ok.


[check_mysql_counters_57_nagios.txt](https://github.com/jasonholtzapple/check_mysql_counters/files/1057931/check_mysql_counters_57_nagios.txt)
[check_mysql_counters_57_pnp4nagios.txt](https://github.com/jasonholtzapple/check_mysql_counters/files/1057933/check_mysql_counters_57_pnp4nagios.txt)

File check_mysql_counters_57_nagios.txt rename it to check_mysql_counters_57 and put it in libexec dir of nagios

File check_mysql_counters_57_pnp4nagios.txt rename it to check_mysql_counters_57.php and put it on pnp4nagios directory where you have templates.

Do not forget to add on my.cnf file 

show_compatibility_56 = on

**Comment by wsams** [comment]
Hello, I have a need for check_mysql_counters_57 on MySQL Community Edition. Yesterday I looked into creating one and it appears to be working so I may submit a PR soon unless one is on the way.

**Comment by jasonholtzapple** [comment]
I'm working on 5.7 Percona but not 5.7 CE so pull request would be welcome!

**Comment by wsams** [comment]
Great @jasonholtzapple . I looked over what has been done in the percona version and it looks similar to what I've been doing. Hopefully next week I'll have a PR.

**Comment by wsams** [comment]
Hi @jasonholtzapple , have you ran into any case sensitivity issues? I'm testing against two MySQL 5.7 instances, and for instance, I had to change,

```
SELECT * FROM INFORMATION_SCHEMA.GLOBAL_STATUS
```

to,

```
SELECT * FROM performance_schema.global_status
```

**Comment by jasonholtzapple** [comment]
Short answer, yes ...

**Comment by wsams** [comment]
@jasonholtzapple , I'm unsure how to do the template. I have some ideas, but maybe you could give me some pointers?

For example, I think $DS[85] comes from one of the references files, but not sure how to generate those?

```
$def[$num] = rrd::def('sel', $RRDFILE[1], $DS[85], 'AVERAGE');
```

**Comment by jasonholtzapple** [comment]
@wsams the reference files are created by hand - just an ordered list of all the parameters output by the plugin. They are useful when first creating a template and if you want to add graphs to a previously created template and don't necessarily have access to that version of MySQL.

**Comment by wsams** [comment]
@jasonholtzapple , that sounds pretty straight forward. Last September my instance quit charting. We accidentally upgraded from 3 to 4 and didn't notice charting stopped. It's a bit hard for me to test at the moment, but I'm working on it.

**Comment by jasonholtzapple** [comment]
Native Percona 5.7 support has been merged in. I will not be working on Vanilla 5.7 but will accept merge requests.
